name: config-project
on: workflow_dispatch
jobs:
    ins_dep:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v6
            - name: Install dependencies
              run: pip install uv 
            - name: Install dependencies
              run: uv sync  
            


    